# Generated by Django 4.1.6 on 2023-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_tags_post_hashtags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
